# Generated by Django 4.1.7 on 2023-03-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activation_phone",
            field=models.CharField(default="1095", max_length=4),
        ),
    ]
