# Generated by Django 4.1.7 on 2023-03-20 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_activation_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="activation_phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verified_phone",
        ),
    ]
