# Generated by Django 4.1.7 on 2023-03-24 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donation",
            old_name="fond",
            new_name="fund",
        ),
    ]
