# Generated by Django 4.1.7 on 2023-03-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("charity_programs", "0001_initial"),
        ("payment", "0004_alter_donation_fund_alter_donation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="charity_prigram",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="donations",
                to="charity_programs.program",
            ),
        ),
    ]
