# Generated by Django 4.1.7 on 2023-03-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.RemoveField(
            model_name="category",
            name="id",
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=150,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
