# Generated by Django 4.1.7 on 2023-03-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reports",
            name="body",
            field=models.TextField(blank=True),
        ),
    ]
