# Generated by Django 4.1.7 on 2023-03-21 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_alter_reports_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reports",
            options={"verbose_name_plural": "Reports"},
        ),
    ]
