# Generated by Django 4.1.7 on 2023-03-17 05:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_rename_image_reportimage_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reportimage",
            old_name="images",
            new_name="image",
        ),
    ]
