# Generated by Django 4.1.7 on 2023-03-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_rename_images_reportimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportimage",
            name="image",
            field=models.ImageField(blank=True, upload_to="reports_photo/"),
        ),
    ]
