# Generated by Django 4.1.7 on 2023-03-22 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="programrating",
            name="rating",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reportrating",
            name="rating",
            field=models.IntegerField(),
        ),
    ]
