# Generated by Django 4.1.7 on 2023-03-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("program_categories", "0001_initial"),
        ("charity_programs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charity_programs",
                to="program_categories.category",
            ),
        ),
    ]
