# Generated by Django 4.1.7 on 2023-03-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity_programs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="program_image",
            field=models.ImageField(blank=True, upload_to="programs/"),
        ),
    ]
